# Generated by Django 4.1.1 on 2022-09-08 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_record_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='habit_tracker.habit'),
        ),
    ]
