# Generated by Django 4.1.1 on 2022-09-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0003_alter_record_habit'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('habit', 'entry_date'), name='unique_user_date'),
        ),
    ]
