# Generated by Django 4.1 on 2022-09-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0005_alter_record_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='entry_date',
            field=models.DateField(),
        ),
    ]
