# Generated by Django 4.1 on 2022-09-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0006_alter_record_entry_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='record',
            name='unique_user_date',
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('habit', 'entry_date'), name='unique_habit_date'),
        ),
    ]
