# Generated by Django 4.1 on 2022-09-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0008_remove_record_unique_habit_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='record',
            name='unique_habit_date',
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('habit', 'entry_date'), name='unique_habit_date'),
        ),
    ]
